### ISSUE TITLE
Support for 1964GEPD Emulator save files

### ISSUE THREAD

**Issue by Millymilo00** [MaikelChan/PDSaveEditor#1]
Hi there, I would love to use this software to transfer my save files from the [1964GEPD](https://github.com/Graslu/1964GEPD) emulator to the PC port, but whenever I try uploading my save data it always says it's not a perfect dark save file. I'm not sure if I'm grabbing the wrong file or if it just isn't supported. 

If it isn't supported, I'd love for this software to be updated to support it.

Thank you!

**Comment by Millymilo00** [comment]
Not sure if I should close this issue because of this but I found a workaround. But,
If I use the program [N64SaveConverter](https://github.com/Ninjiteu/N64SaveConverter) and convert the save data in 1964GEPD to retroarch, then back to `.eep`, I'm able to open it up with this program.

**Comment by MaikelChan** [comment]
Hi, I'm glad you found a solution!

I took a look at the issue, and turns out that the format is correct, it's just that 1964 adds 2kb extra padding to the save file, making it 4kb in total. The save should be 2kb total. So another solution would have been just remove the last 2kb of bytes with an hex editor.

The file size check the program does is one of the checks to make sure the user is opening a valid Perfect Dark save, and not from another game or format, to prevent crashes.
